### ISSUE TITLE
VSCode in disconnected environment pops-up an `Error loading webview`

### ISSUE THREAD

**Issue by jstourac** [opendatahub-io/notebooks#349] opened 2023-11-15 23:20 UTC
**What steps did you take and what happened:**
I started the latest build of the [VSCode server](https://quay.io/repository/opendatahub/workbench-images/manifest/sha256:94426688c02853438a9f11fdd420c1af20946e521773aec16700bb3766864375) in a cluster in disconnected environment via JupyterHub spawner. Once I navigated into the VSCode IDE UI in my browser, I can see an error as a pop-up message in lower right corner and available also in the IDE output window:

```
[error] [Service Worker] registration Failed to register a ServiceWorker for scope ('https://jupyter-nb-***-rhods-notebooks.apps.***.com/vscode/') with script ('https://jupyter-nb-***-rhods-notebooks.apps.***.com/vscode/_static/out/browser/serviceWorker.js'): An SSL certificate error occurred when fetching the script.
```
(the `***` is shortened text)

**What did you expect to happen:**
No error message shown in the UI

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- OpenDatahub Version: (please check the operator version)
- Workbench: vscode
- Workbench Version: (2023.1, etc)
- Specific tool: vscode
- Notebook-Controller Version: (please check the image version in notebook-controller deployment)

**Logs/Screenshots**

**Comment by rkpattnaik780** [comment] 2023-11-16 06:55
Possible duplicate of #348.

**Comment by harshad16** [comment] 2024-01-22 17:47
Please track further work in JIRA: https://issues.redhat.com/browse/RHOAIENG-234
closing this issue.

**Closed by harshad16** 2024-01-22 17:47 UTC
Labels: kind/bug, feature/vscode
