### ISSUE TITLE
The data science anaconda notebook fails to build on openshift CI

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#195] opened 2023-09-01 08:34 UTC
When attempting to build the Data Science Anaconda Notebook on Openshift CI as part of the test run, the build process encounters an error. 
The failure occurs in the Dockerfile at [this line](https://github.com/opendatahub-io/notebooks/blob/main/jupyter/datascience/anaconda-python-3.8/Dockerfile#L31). The error message received is "DockerBuildFailed: Dockerfile build strategy has failed."
That build error has been observed recently, on this link are the detailed logs [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/opendatahub-io_notebooks/188/pull-ci-opendatahub-io-notebooks-main-jupyter-datascience-anaconda-python-3-8-pr-image-mirror/1696795994106105856).

**Comment by jstourac** [comment] 2023-09-04 11:55
Just providing some data since the originally linked run isn't available anymore.

Reason for this issue are conflicting packages found during the following command:

```
/opt/anaconda3/bin/conda env update -p "${APP_ROOT}" --file environment.yml
```

```
STEP 11/19: RUN echo "Installing softwares and packages" &&     /opt/anaconda3/bin/conda env update -p "${APP_ROOT}" --file environment.yml &&     rm -f ./environment.yml &&     mkdir /opt/app-root/runtimes &&     cp utils/pipeline-flow.svg /opt/app-root/lib/python3.8/site-packages/elyra/static/icons/kubeflow.svg &&     sed -i "s/Kubeflow Pipelines/Data Science/g" /opt/app-root/lib/python3.8/site-packages/elyra/pipeline/runtime_type.py &&     sed -i "s/Kubeflow Pipelines/Data Science Pipelines/g" /opt/app-root/lib/python3.8/site-packages/elyra/metadata/schemas/kfp.json &&     sed -i "s/\"default\": \"Argo\",/\"default\": \"Tekton\",/g" /opt/app-root/lib/python3.8/site-packages/elyra/metadata/schemas/kfp.json &&     sed -i -e "s/Python.*/$(python --version)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json &&     rm /opt/app-root/share/jupyter/metadata/runtime-images/*.json &&     chmod -R g+w /opt/app-root/lib/python3.8/site-packages &&     fix-permissions /opt/app-root -P
Installing softwares and packages
Collecting package metadata (repodata.json): ...working... WARNING conda.models.version:get_matcher(548): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(548): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
WARNING conda.models.version:get_matcher(548): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(548): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

The report with conflicts is several thousand lines long...

This can be reproduced locally too by first building base image and then the jupyter-datascience-anaconda one:

```
cd base/anaconda-python-3.8
podman build .
<note the build hash>
cd ../../jupyter/datascience/anaconda-python-3.8
podman build . -f my.Dockerfile --build-arg BASE_IMAGE=<base build hash>
```

**Comment by Xaenalt** [comment] 2023-09-06 14:29
Yeah, need to update the package list, I'll rerun that when I get a couple hours

**Comment by harshad16** [comment] 2023-10-16 12:37
The PR: https://github.com/openshift/release/pull/44385 would be temporarily disabling conda image built
Till we fix this issue.

**Comment by Xaenalt** [comment] 2023-10-16 19:06
Yes, you have my blessing to disable it until I can finally get back to fixing it

**Comment by jstourac** [comment] 2024-02-02 18:11
@harshad16 I opened this one openshift/release#48398 to revert the disabled CI checks for anaconda image.

**Comment by harshad16** [comment] 2024-02-02 18:37
Thanks for the work :100:

**Comment by harshad16** [comment] 2024-05-10 16:53
With the revert of https://github.com/openshift/release/pull/48398
This issue is fixed. Closing the issue.

**Closed by harshad16** 2024-05-10 16:53 UTC
Labels: kind/bug, priority/major
